name: Publish artifact to GHCR (prod)
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: master
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PASSWORD }}
    - name: Build Docker using Dockerfile
      uses: docker/build-push-action@v3.1.1
      with:
        context: .
        push: true
        tags: |
          ghcr.io/borrowwing/emotion:latest
        platforms: linux/amd64
    - name: Calling webhook to re-build
      run: "curl -k --data '' -w '%{http_code}' ${{ secrets.WEBHOOK_URL }}"
